# Generated by Django 4.0.5 on 2022-07-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewTag',
            new_name='TagReview',
        ),
    ]
